package com.facturacion_Entrega.facturacion.Entity;
import jakarta.persistence.CascadeType;
import java.util.List;

//import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

@Entity
@Table(name = "clients")
public class client {
   

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
   // @Schema(description = "Client ID is autogenerated", hidden = true)
    private Long clientId;

    @Schema(description = "Client Name", example = "Lucas", requiredMode="", hidden = false) //= Schema.RequiredMode.REQUIRED, hidden = false)
    private String clientName;

    @Schema(description = "Client Lastname", example = "López", requiredMode="", hidden = false) //= Schema.RequiredMode.REQUIRED, hidden = false)
    private String clientLastname;

    @Schema(description = "Client Document Number", example = "10203040", requiredMode="", hidden = false) //= Schema.RequiredMode.REQUIRED, hidden = false)
    private String docnumber;

    //@JsonIgnore
    @OneToMany(mappedBy = "client", cascade = CascadeType.MERGE)
    private List<invoices> invoices;

//contructores vacio y con argumentos
    public client() {
       
    }
    public client(Long id, String name, String lastname, String docnumber) {
        this.clientId = id;
        this.clientName = name;
        this.clientLastname = lastname;
        this.docnumber = docnumber;
    }

    public Long getClientId() {
        return clientId;
    }

    public void setClientId(Long clientId) {
        this.clientId = clientId;
    }

    public String getClientName() {
        return clientName;
    }

    public void setClientName(String clientName) {
        this.clientName = clientName;
    }

    public String getClientLastname() {
        return clientLastname;
    }

    public void setClientLastname(String clientLastname) {
        this.clientLastname = clientLastname;
    }

    public String getDocnumber() {
        return docnumber;
    }

    public void setDocnumber(String docnumber) {
        this.docnumber = docnumber;
    }

    public List<invoices> getInvoices() {
        return invoices;
    }

    public void setInvoices(List<invoices> invoices) {
        this.invoices = invoices;
    }

}