package com.facturacion_Entrega.facturacion.Entity;

import java.util.Date;
import java.util.List;

//import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;

@Entity
@Table(name = "invoice")
public class invoices {
   

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    //@Schema(description = "Invoice ID is autogenerated", hidden = true, example = "", requiredMode = "")
    private Long invoiceId;

    @Column(name = "created_at")
    //@Schema(hidden = true)
    private java.sql.Date createdAt;

    @Column(name = "total")
    @Schema(description = "Total invoice price", example = "1984.00", hidden = true, requiredMode = "")
    private Double total;

    @Schema(description = "Total products in invoice", example = "1", requiredMode = "", hidden = false)
    @Column(name = "total_product")
    private int totalProduct;

    @ManyToOne(cascade = CascadeType.MERGE)
    @JoinColumn(name = "client_id")
    @Schema(description = "Client ID", requiredMode ="", example = "1987", hidden = false) //Schema.RequiredMode.REQUIRED, example = "", hidden = false)
    private client client;

    @OneToMany(cascade = CascadeType.ALL, orphanRemoval = true)
    @Schema(description = "Invoice Details", requiredMode ="", example = "2", hidden = false) //Schema.RequiredMode.REQUIRED, example = "", hidden = false)
    private List<invoice_details> invoiceDetails;

     public invoices() {
       
    }
    public invoices(Long id, client client, java.sql.Date createdAt, double total, int totalProduct) {
        this.invoiceId = id;
        this.client = client;
        this.createdAt = createdAt;
        this.total = total;
        this.totalProduct = totalProduct;
    }

    public Long getInvoiceId() {
        return invoiceId;
    }

    public void setInvoiceId(Long invoiceId) {
        this.invoiceId = invoiceId;
    }

    public Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(java.sql.Date createdAt) {
        this.createdAt = createdAt;
    }

    public Double getTotal() {
        return total;
    }

    public void setTotal(Double total) {
        this.total = total;
    }

    public client getClient() {
        return client;
    }

    public void setClient(client client) {
        this.client = client;
    }

    public List<invoice_details> getInvoiceDetails() {
        return invoiceDetails;
    }

    public void setInvoiceDetails(List<invoice_details> invoiceDetails) {
        this.invoiceDetails = invoiceDetails;
    }

    public void setTotalProduct(int totalProduct) {
        this.totalProduct = totalProduct;
    }

    public int getTotalProduct() {
        return totalProduct;
    }
}